export const productlist = [
  {
    name: "headphone",
    price: 200,
    discount: 15,
    image: "/product/grant-ritchie-n_wXNttWVGs-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "alex motoc",
    price: 220,
    discount: 15,
    image: "/product/alex-motoc-0POwK6iAiRQ-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "alexander andrews",
    price: 320,
    discount: 15,
    image: "/product/alexander-andrews-BX4Q0gojWAs-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "charlesdeluvio",
    price: 500,
    discount: 15,
    image: "/product/charlesdeluvio-1-nx1QR5dTE-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "headphone",
    price: 200,
    discount: 15,
    image: "/product/jakob-owens-BmH09wAkJa8-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "alex motoc",
    price: 220,
    discount: 15,
    image: "/product/kiran-ck-LSNJ-pltdu8-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "alexander andrews",
    price: 320,
    discount: 15,
    image: "/product/samsung-memory--9qtL6q7cyY-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
  {
    name: "charlesdeluvio",
    price: 500,
    discount: 15,
    image: "/product/taras-chernus-eSIlQfibAo8-unsplash.jpg",
    feature: [
      { title: " MPN: JBLFLIP5GRYAM" },
      { title: "Model: FLIP 5" },
      { title: "Frequency response: 65Hzâ€“20kHz" },
      { title: " Transducer: 44mm x 80mm" },
      { title: "IPX7 waterproof design" },
      { title: " 12 hours of playtime" },
    ],
  },
];
